namespace MissionPlanner.Core.Setup.Reporting;

internal sealed record SetupReportDefinition(string Title, string Overview, string Guidance, string[]? Prefixes);

internal static class SetupReportDefinitions
{
    internal static SetupReportDefinition Get(SetupReportTopic topic) => topic switch
    {
        SetupReportTopic.Frame => new("Frame", "Frame class and geometry reported by the flight controller.", "Review the frame selection in Configuration before writing and verifying it.",
            ["FRAME_", "Q_FRAME_"]),
        SetupReportTopic.Accelerometer => new("Accelerometer", "Accelerometer calibration and board orientation.", "Remove propellers and keep the vehicle disarmed. Follow the requested orientation during calibration.",
            ["INS_ACC", "INS_ACCOFFS", "INS_ACCSCAL", "AHRS_ORIENTATION", "AHRS_TRIM"]),
        SetupReportTopic.Radio => new("Radio", "Receiver input mapping and confirmed channel calibration.", "Turn on the transmitter and remove propellers. Capture, review and confirm endpoints in Configuration.",
            ["RC", "FLTMODE_CH", "MODE_CH"]),
        SetupReportTopic.ServoOutput => new("Servo output", "Output functions, reversal and confirmed PWM limits.", "Confirm physical wiring independently. Output function numbers alone do not identify attached hardware.",
            ["SERVO", "BRD_PWM"]),
        SetupReportTopic.SerialPorts => new("Serial ports", "Serial protocols, baud settings and port options.", "SERIAL indexes do not establish physical UART wiring. Confirm required reboots after changes.",
            ["SERIAL"]),
        SetupReportTopic.EscMotor => new("ESC and motors", "Motor output and ESC calibration configuration.", "Remove all propellers before motor tests. Use bounded tests and keep the stop action accessible.",
            ["MOT_", "Q_M_", "ESC_", "SERVO_BLH", "FRAME_", "Q_FRAME_"]),
        SetupReportTopic.FlightModes => new("Flight modes", "Reported flight-mode slots and mode-channel selection.", "Review transmitter switch positions and the firmware-supported mode choices in Configuration.",
            ["FLTMODE", "MODE", "RC"]),
        SetupReportTopic.FailSafe => new("Failsafe", "Reported failsafe thresholds and actions.", "Review the effect of each failsafe action for this vehicle and flight environment before applying it.",
            ["FS_", "BATT_FS", "BATT_LOW", "BATT_CRT", "THR_FAILSAFE", "THR_FS", "FENCE_"]),
        SetupReportTopic.InitialTune => new("Initial tuning", "Filter, acceleration and motor settings used during initial tuning.", "These settings affect flight behaviour. Apply reviewed values and use appropriate flight-test precautions.",
            ["ATC_", "Q_A_", "ACRO_", "INS_ACCEL_FILTER", "INS_GYRO_FILTER", "MOT_", "Q_M_", "BATT_ARM_VOLT", "BATT_CRT_VOLT", "BATT_LOW_VOLT"]),
        SetupReportTopic.HardwareId => new("Hardware identification", "Board and sensor identification evidence.", "Reported identifiers are diagnostic evidence; they do not by themselves confirm wiring or sensor health.",
            []),
        SetupReportTopic.Firmware => new("Firmware", "Firmware identity and preparation for a verified upgrade.", "USB discovery and bootloader identity are separate from a vehicle telemetry connection. Select, validate and install firmware in Configuration.",
            []),
        SetupReportTopic.Airspeed => new("Airspeed", "Airspeed sensor types, use flags and calibration settings.", "Review the physical sensor and pressure connections before enabling airspeed use.",
            ["ARSPD"]),
        SetupReportTopic.Battery => new("Battery monitors", "Battery monitor types, capacity and failsafe configuration.", "Use an independent reference when calibrating voltage or current. Verify the correct battery instance before writing.",
            ["BATT"]),
        SetupReportTopic.CameraGimbal => new("Camera and gimbal", "Reported camera and mount configuration.", "Live camera and gimbal operation remains in Payload Control.",
            ["CAM", "MNT", "MOUNT", "GMBL"]),
        SetupReportTopic.CanGpsOrder => new("CAN GPS order", "GPS node ordering and override configuration.", "Match node identifiers to the intended physical GPS receivers before applying overrides.",
            ["GPS1_CAN_OVRIDE", "GPS2_CAN_OVRIDE", "GPS_CAN_NODEID"]),
        SetupReportTopic.CompassMotor => new("Compass / motor calibration", "Motor interference compensation for the compass.", "Remove all propellers. CompassMot can spin motors; start and stop it from Configuration.",
            ["COMPASS_MOT", "COMPASS_MOTCT"]),
        SetupReportTopic.DroneCan => new("DroneCAN / UAVCAN", "Reported CAN bus configuration.", "Connect to a supported transport in Configuration to inspect nodes. Vehicle parameters alone do not prove a node is online.",
            ["CAN_", "CAN_D", "CAN_P"]),
        SetupReportTopic.Naming => new("Vehicle identifiers", "Confirmed vehicle identifiers used for addressing and identification.", "Changing the system ID may require reconnecting. Local edits are separate from the confirmed values shown here.",
            ["MAV_SYSID", "SYSID_THISMAV", "BRD_SERIAL_NUM"]),
        SetupReportTopic.OnboardOsd => new("Onboard OSD", "Onboard display configuration reported by the vehicle.", "Open the authoritative Onboard OSD editor from Configuration.",
            ["OSD"]),
        SetupReportTopic.OpticalFlow => new("Optical flow", "Optical-flow sensor configuration.", "Confirm sensor orientation and the required range/height source before using optical flow.",
            ["FLOW_"]),
        SetupReportTopic.Parachute => new("Parachute", "Parachute enablement and release configuration.", "This setup page configures parameters and does not deploy the parachute.",
            ["CHUTE_"]),
        SetupReportTopic.Rangefinder => new("Rangefinder", "Rangefinder types, limits and orientation.", "Verify the correct sensor instance, mounting direction and valid measurement range.",
            ["RNGFND"]),
        SetupReportTopic.AntennaTracker => new("Antenna tracker", "Tracker configuration reported by the connected firmware.", "Actuator testing is unavailable until a bounded tracker-specific output adapter and operation gate are available.",
            ["SERVO", "YAW_", "PITCH_", "TRIM_", "TRACK_"]),
        SetupReportTopic.Bluetooth => new("Bluetooth serial module", "Direct serial configuration of a supported Bluetooth module.", "Select a serial port and probe the module in Configuration. A vehicle telemetry connection does not identify this external module.",
            null),
        SetupReportTopic.SikRadio => new("SiK radio", "Direct serial configuration of a SiK telemetry radio.", "Connect and read the radio before changing settings. Apply, save and reboot remain explicit actions in Configuration.",
            null),
        SetupReportTopic.RtkGps => new("RTK / GPS injection", "Correction-source connection and delivery to the selected vehicle.", "Select the correction source in Configuration. A connected source is separate from confirmation that corrections are being received by the vehicle.",
            null),
        SetupReportTopic.Joystick => new("Joystick", "Local joystick selection and vehicle-output availability.", "Select a supported device in Configuration. Vehicle output requires a supported output adapter; disabling releases control.",
            null),
        SetupReportTopic.CubeId => new("CubeID update", "Local CubeID firmware inspection and target detection.", "Inspect a local image in Configuration. Updating remains unavailable until a compatible target is detected.",
            null),
        SetupReportTopic.Esp8266 => new("ESP8266", "Wi-Fi settings validation for an ESP8266 component.", "Configure and validate settings in Configuration. Credentials are never included in reports; validation does not prove that settings were written to a device.",
            null),
        SetupReportTopic.Fft => new("FFT analysis", "Frequency analysis of an existing DataFlash sample export.", "Supply exported samples and their sample rate in Configuration. This tool does not download logs.",
            null),
        SetupReportTopic.MotorTest => new("Motor test", "Motor assignments and confirmed spin thresholds.", "Remove ALL propellers. Motors will spin during tests. Review physical motor mapping and use the bounded controls in Configuration.",
            ["FRAME_", "Q_FRAME_", "MOT_", "Q_M_", "SERVO"]),
        SetupReportTopic.Adsb => new("ADS-B", "ADS-B receiver and transponder configuration.", "Confirm device compatibility and required identifiers before applying transponder settings.",
            ["ADSB_"]),
        _ => throw new ArgumentOutOfRangeException(nameof(topic), topic, "Unknown setup report topic."),
    };
}
