namespace MissionPlanner.App.Presentation.Documents;

/// <summary>Offline, task-oriented help for every visible hardware and configuration section.</summary>
public static class SectionHelpCatalog
{
    private const string Mandatory = "Mandatory Hardware";
    private const string Optional = "Optional Hardware";
    private const string Configuration = "Configuration";
    private const string SetupDocs = "https://ardupilot.org/copter/docs/configuring-hardware.html";
    private const string PeripheralDocs = "https://ardupilot.org/copter/docs/common-optional-hardware.html";

    public static IReadOnlyList<SectionHelp> Sections { get; } =
    [
        T("Application", "Flight Data",
            "Monitor the active vehicle through the HUD, mission map and telemetry panels, and access supported vehicle commands. Reset model heading captures a display-only reference for the HUD heading arrow; Restore heading removes it. The 2D cockpit horizon and compass remain unchanged. Fresh attitude is required; changing vehicle/session clears the reference.",
            "Confirm the vehicle identity, connection state and live telemetry before interpreting displayed values.|Use Quick and Gauges for selected readings, Status for detailed telemetry, and Messages for vehicle-reported information and warnings.|Review PreFlight before operation. Use Actions only after checking the requested command and target.|To access storage as a USB drive on compatible controllers and firmware, keep the vehicle disarmed and select Actions > Reboot to USB storage. Review and confirm the restart; the action is unavailable when the reboot checks are not satisfied.|Connect by USB and check whether the operating system exposes the controller's storage. When finished, safely eject the drive and restart the controller to return to normal operation, then reconnect telemetry.|Servo/Relay, Aux Function and Payload Control can affect connected hardware; review output assignments and keep mechanisms clear.|Use DataFlash Logs for the vehicle's onboard recordings; use the separate Logs workspace for PC telemetry recordings and application diagnostics.",
            "Check fresh telemetry and the vehicle's reported state after a command. For USB storage, read the command result and verify that the drive actually appears. A command acknowledgement or lost telemetry connection alone does not prove that storage mounted successfully.",
            "Reboot to USB storage interrupts telemetry and control and requires compatible firmware and hardware. It runs only when you request and confirm it. Use Configuration > Mavlink Ftp for file access over a supported telemetry connection instead. Recorded or stale data is not live vehicle evidence. Review Scripts before execution and remove propellers for bench actuator checks.",
            "https://ardupilot.org/planner/docs/mission-planner-flight-data.html"),
        T("Application", "Flight Planner",
            "Create and edit a local mission, save it to a file, and explicitly transfer it to or from the intended vehicle.",
            "Load a mission file or read the existing mission from the vehicle before editing it.|Review waypoint order, command types, coordinates, altitude reference and command-specific fields in the map and mission list.|Apply row edits to the local mission or use Revert to discard them. Save a local file when you need a backup.|Use Write mission to vehicle only after reviewing the destination and complete mission.|Read the mission back and compare its important commands and geometry before starting it.",
            "Verify mission item count, order, altitude references and the intended end-of-mission action. Check terrain and operating limits independently.",
            "Apply commits local row edits; it does not upload the mission. Clear the local mission does not by itself clear the vehicle's mission. Uploading does not automatically execute a mission.",
            "https://ardupilot.org/planner/docs/mission-planner-flight-plan.html"),
        T("Application", "Preferences",
            "Configure how this application displays information and manages local resources.",
            "Review the relevant settings group, including appearance, units, maps and telemetry preferences.|Use Save preferences after reviewing changes; export a copy before resetting or importing settings.|Configure a map credential with its dedicated save/test controls when a provider requires one.|For offline use, import or install a supported map pack, select it, and verify the pack.|Use section resets for a limited change; Reset all affects the broader preferences collection.",
            "Reopen the relevant settings and check the resulting display or map behaviour. Check units again before entering mission or tuning values.",
            "Application preferences are separate from flight-controller parameters. Clearing a map cache removes cached map data; it does not repair vehicle telemetry. Review exported settings before sharing them.",
            "https://ardupilot.org/planner/docs/mission-planner-configuration-and-tuning.html"),
        T("Application", "Simulation",
            "Prepare and run a supported software-in-the-loop scenario to exercise workflows without a physical airframe.",
            "Choose the vehicle, model and available simulation runtime or release.|Review the starting location, home, connection endpoints and scenario options before launch.|Inspect additional arguments and environment settings if you use them; load or save a scenario preset for repeatable setup.|Use Start and watch the process output and status. Check the app's connection and simulated vehicle identity before issuing commands.|Use Stop when finished, or Restart when the reviewed scenario needs a fresh run.",
            "Confirm both that the simulator is running and that telemetry belongs to the expected simulated vehicle. If startup fails, inspect the runtime path, process output and endpoint conflicts.",
            "A running process is not proof of a telemetry connection. A successful simulation does not validate physical wiring, motor order or real-airframe tuning. Keep live hardware connections distinct from simulation.",
            "https://ardupilot.org/dev/docs/sitl-simulator-software-in-the-loop.html"),
        T("Application", "Arming",
            "Inspect reported arming evidence, review supported arming settings and explicitly request arm or disarm.",
            "Read Information for the current vehicle state and reported problems.|Refresh cached arming evidence after relevant changes, and use Messages or the live Inspector when you need further context.|In Configuration, review pending parameter changes. Stage firmware default changes only when appropriate, then use Apply and verify to write them.|Use Discard pending changes to abandon local edits or open Parameters Editor for additional supported settings.|Only use Arm Vehicle or Disarm Vehicle when the vehicle state and surroundings are appropriate.",
            "Check the vehicle's reported armed state and any rejection messages. Review readback and required reboots after parameter changes.",
            "Refreshing cached evidence does not run a new physical safety test. Do not disable checks just to bypass a reported fault, and do not treat a sent arm command as a successful arm.",
            "https://ardupilot.org/copter/docs/configuring-hardware.html"),
        T("Application", "Advanced",
            "Discover the implemented advanced tools and review their requirements before opening them.",
            "Select a tool in the Advanced list and read its description and availability status.|Check whether the tool needs an active vehicle, particular firmware support, local data or another connection.|Open the available tool and review its target and operation scope before starting.|For analysis tools, select the intended recording or data source; for hardware tools, verify the connected device and supported controls.|Inspect the tool's result and retain relevant diagnostics before returning to the main workspace.",
            "Confirm whether the result came from live telemetry, recorded data or a completed hardware operation. Check reported failures instead of assuming a tool ran.",
            "Unavailable tools are not completed operations. Output and device-management tools may change hardware state; a telemetry-inspection tool does not establish that the hardware is safe.",
            "https://ardupilot.org/planner/docs/mission-planner-flight-data.html"),
        T("Application", "Connect / Vehicle Connection",
            "Select and establish a supported serial or network connection to an ArduPilot vehicle.",
            "Power the intended device, open Connect and refresh the available channels.|For serial, choose the controller's port and correct baud rate. UDP Listen waits on a local port; leave its optional bind address blank to listen on all interfaces. UDP Client requires a remote host and port and sends a GCS heartbeat so the peer can learn the return address.|WebSocket requires a full ws:// or wss:// URL and a server carrying raw binary MAVLink, not JSON or Socket.IO. WSS uses normal certificate validation. Network transports do not use baud rate.|Opening a socket is followed by waiting for a vehicle heartbeat; it does not establish arming readiness. Network settings are remembered separately when you connect or close with the check button; URLs containing query tokens stay in memory only.|Choose AUTO if you want discovery when you click Connect: one available serial device is preferred; multiple devices require an explicit selection.|With no serial device available, AUTO listens for an ArduPilot UDP heartbeat on the configured local port, using 14550 as the fallback. If none is found, it reports that no endpoint was detected.|After connection, verify the displayed vehicle identity and live telemetry. Use Disconnect before handing the same connection resource to another tool.",
            "A listed COM port is only a connection candidate. Check the successful vehicle handshake and live status; inspect the connection message if discovery or identification fails.",
            "AUTO discovery runs when you request Connect, not merely at app startup. Known incompatible serial devices are filtered, but a port name cannot prove firmware identity. STM32 DFU bootloaders belong in Install Firmware, not a normal telemetry connection.",
            "https://ardupilot.org/copter/docs/initial-setup.html"),
        T("Application", "Logs",
            "Inspect PC telemetry recordings and application diagnostics, keeping them distinct from onboard DataFlash logs.",
            "In Telemetry Logs, check recording state, file path, byte count and recording errors.|Refresh recordings, select a session and use View packets, replay, or export as appropriate; import a .tlog when working with an external recording.|Check recording identity and time before analysis. Use Flight Data's DataFlash Logs tab for the vehicle's onboard log workflow.|In Application Logs, select the current session or a historical file and filter by severity, source, text or UTC time.|Copy or export the relevant event or view when investigating an issue. Review the contents before sharing, and back up a recording before deleting it.",
            "Check that recording size increases while telemetry is being captured and that the selected log covers the time of the issue. A display filter may hide useful context.",
            "Replay is recorded data, not a live connection. Clear view only does not delete the underlying application log. Recording level and display filters serve different purposes; verbose recording can produce substantially more data.",
            "https://ardupilot.org/planner/docs/mission-planner-flight-data.html"),
        T(Mandatory, "Frame",
            "Select the vehicle frame class and geometry so the flight controller uses the appropriate motor layout.",
            "Identify the physical frame and controller orientation.|Review the supported frame choices and apply the matching selection.|Complete any requested reboot, then use Motor Test to check each motor against the motor-order diagram.",
            "Check the frame reported by the vehicle after reconnecting. A matching motor count alone does not establish the correct geometry.",
            "Remove propellers before checking motor order. Do not copy another vehicle's frame settings without checking its geometry."),
        T(Mandatory, "Accel Calibration",
            "Calibrate accelerometer offsets and establish the controller's orientation and level reference.",
            "Place the disarmed vehicle on a stable surface with propellers removed.|Check board orientation, then start calibration and follow each requested position.|Keep the vehicle still for each measurement and wait for the completion message.",
            "Return the vehicle to level and check that the attitude display agrees with its actual orientation.",
            "If a position fails, check movement and orientation before repeating calibration; do not compensate for incorrect mounting with arbitrary trim."),
        T(Mandatory, "Compass",
            "Identify and calibrate the compasses used for heading estimation.",
            "Review detected devices, orientation and priority before starting.|Move away from magnetic objects and high-current wiring, then follow the calibration prompts.|Review the result for each compass and complete any requested reboot.",
            "Check that heading changes consistently when the vehicle turns. Recheck device identity after replacing a GPS/compass unit.",
            "A successful calibration does not prove that motor interference is acceptable."),
        T(Mandatory, "Radio Calibration",
            "Capture receiver channel endpoints and verify stick mapping.",
            "Turn on the transmitter, connect the receiver and remove propellers.|Check channel movement, then run the capture workflow and move the requested controls through their full range.|Review endpoints, centre positions and channel mapping before confirming.",
            "With the vehicle disarmed, move pitch forward/backward and roll left/right independently. Open channel details to compare raw input with the mapped axis, received calibration and local interpreted direction. For Copter, verify forward pitch gives nose-down and right roll gives roll-right. Raw PWM is received before FC reversal and does not change when RCx_REVERSED changes. Missing mapping/calibration prevents a reliable local interpretation. Check flight-mode switches separately.",
            "Keep trims and transmitter configuration consistent with the calibration. Verify receiver-loss behaviour in Failsafe."),
        T(Mandatory, "Servo Output",
            "Assign output functions, reversal, trim and limits, and monitor reported output PWM values in compact channel rows.",
            "Connect the intended vehicle, load its parameters and refresh Servo Output. Match physical wiring to the controller's output labels.|In Configuration, review the reported channels. The page supports channels up to 32 when their parameters are available; unsupported fields remain unavailable.|Choose each channel's function from its firmware metadata and edit only the intended reversal, minimum, trim and maximum values.|Use Write to save modified rows and inspect the readback result. If a write fails, resolve the reported problem before retrying the remaining changes.|Watch the live PWM bars and values where telemetry is available. Use the appropriate separate motor or servo test workflow to verify physical movement after configuration.",
            "Check confirmed settings, output direction and mechanical travel without binding. An unavailable live value is shown as a dash; configuration support for channels 17–32 does not imply live telemetry for those channels. A PWM reading does not prove that the connected actuator moved.",
            "Remove propellers and keep mechanisms clear. A function number does not identify what is physically connected. Missing fields depend on the parameters reported by the firmware. Do not assume a serial, CAN or timer-group output behaves like an ordinary PWM servo."),
        T(Mandatory, "Serial Ports",
            "Configure the protocol, baud rate and options used by each controller serial port.",
            "Consult the board wiring documentation to map SERIAL indices to connectors.|Select settings required by the attached peripheral and review pending changes.|Apply, reboot when required, and reconnect before checking the peripheral.",
            "Look for actual device data rather than treating a stored protocol value as proof of communication.",
            "Changing the port carrying telemetry can disconnect the app. Record the original settings and a recovery connection first."),
        T(Mandatory, "ESC Calibration",
            "Review motor output configuration and the calibration workflow appropriate to the ESC protocol.",
            "Identify the ESC model, protocol and supported controller outputs.|Read the workflow instructions before starting any calibration or power-cycle sequence.|After completion, verify output configuration and use short Motor Test commands.",
            "Check that the expected motors respond consistently and stop correctly.",
            "Remove all propellers. ESC calibration requirements depend on the protocol; do not apply a PWM calibration sequence to every ESC type.",
            "https://ardupilot.org/copter/docs/common-escs-and-motors.html"),
        T(Mandatory, "Flight Modes",
            "Assign supported flight modes to the receiver's mode-switch positions.",
            "Confirm the configured mode channel and receiver input. The six slots represent PWM bands; a three-position switch may select only slots 1, 4 and 6.|Choose a suitable mode in a slot, then use that row's Apply button to write only that changed assignment. Selecting a dropdown entry alone does not write parameters.|Unknown mode values remain visible in their own slots until explicitly replaced. Parameter not loaded means no value has been received; wait for loading before editing that row.|With the vehicle disarmed, move the switch through every position and review the assignments.",
            "Check confirmed readback and the vehicle's reported active mode. The highlighted RC slot and its configured assignment do not prove that the vehicle entered that mode. Check prerequisites for navigation-dependent modes.",
            "The mode list uses the connected firmware family's catalogue. Copter Acro is mode 1; catalogue membership does not guarantee that the connected firmware build supports a mode. Keep a familiar recovery mode accessible and verify failsafe actions independently."),
        T(Mandatory, "Failsafe",
            "Review actions for loss of radio, telemetry, battery reserve and other supported failure conditions.",
            "Read the descriptions for the connected firmware and vehicle type.|Choose thresholds and actions appropriate to the battery, navigation capability and operating area.|Apply changes, read them back, then follow the documented disarmed test procedure.",
            "Check the observed failsafe indication and resulting action. A threshold saved in the editor is not a functional test.",
            "Do not disable a failsafe simply to clear a warning. Several failsafe conditions may occur together."),
        T(Mandatory, "Initial Tune Params",
            "Review the initial filter, acceleration and motor settings used before detailed flight tuning.",
            "Complete frame, sensor, radio and motor setup first.|Review the available fields and their units against the actual vehicle.|Apply a small reviewed set of changes and retain a known-good parameter backup.",
            "Check confirmed values and required reboots before proceeding to the firmware's first-flight and tuning procedure.",
            "Values are not universal across airframes. This page does not establish that a vehicle is ready to fly."),
        T(Mandatory, "Hardware ID",
            "Inspect board identification and decoded sensor device IDs in a read-only diagnostic view.",
            "Connect the intended vehicle, load its parameters and refresh Hardware ID.|Read Information for the board summary, then open Diagnostics for the identifier table.|Use Parameter and Raw ID to identify the source value; raw IDs include decimal and hexadecimal forms. For supported packed device IDs, review Bus type, Bus, Address and Sensor.|Record or compare these values before and after replacing a compass, barometer, airspeed sensor or IMU. Match the results to the intended device and board documentation.",
            "Unknown bus or sensor codes remain numeric, and identifiers that cannot be decoded show unavailable fields. Ordinary identifiers are not interpreted as packed sensor IDs. If data is missing, check parameter loading and firmware support before concluding that hardware is absent.",
            "This page does not write identifiers or change sensor configuration. A decoded ID is diagnostic evidence; it does not prove sensor health, wiring correctness or exact firmware compatibility."),
        T(Mandatory, "ADS-B",
            "Review and edit the ADS-B and avoidance settings reported by the connected firmware, including receiver and transponder configuration.",
            "Identify the installed device and its connection requirements. Open Information for context and Configuration for the reported ADSB_ and AVD_ parameters.|Search parameter names or descriptions to narrow the list. Mark frequently used settings as Favorite to keep them at the top; favorites are saved locally.|Review descriptions, units and firmware limits. Use the available numeric fields, choice lists or named option checkboxes; unnamed option bits are preserved.|Use Apply on one row, or Apply modified (Ctrl+S) for all pending changes, including rows hidden by the search filter. Batch writes apply enable flags last.|Read the write report. A failed or unconfirmed write stops the batch and leaves pending changes for review. Complete any required controller reboot.|Use Reload from vehicle to request fresh parameters. Pending edits are preserved for the same vehicle; selecting a different vehicle clears those edits.",
            "Check matching vehicle readback for each applied value and confirm that traffic or device status is actually received. A current value outside the metadata limits is retained with a warning for review. Distinguish receiver data, avoidance behaviour and transponder configuration, and verify the intended device instance.",
            "Only parameters reported by the firmware are shown; their presence does not prove that an ADS-B device is attached. Use the device documentation and the correct assigned identity, including its ICAO address where applicable. Refreshing or reloading data is not the same as applying pending edits."),
        T(Mandatory, "Safety",
            "Review safety-switch, arming and related protective settings exposed for the current vehicle.",
            "Read the current state and any reported arming failures.|Resolve the underlying setup or sensor issue before editing safety settings.|Apply intentional changes and verify the safety switch and arming indications while disarmed.",
            "Confirm which outputs remain inhibited and which checks still apply after any required reboot.",
            "Do not treat clearing a warning by disabling a check as a repair."),
        T(Mandatory, "Summary",
            "Review setup status and identify remaining configuration work.",
            "Refresh after completing calibration or parameter changes.|Read each reported item and return to its setup section where further work is needed.|Recheck the summary after required reboots and reconnection.",
            "Distinguish confirmed values, missing information and unresolved warnings. Verify physical wiring and movement separately.",
            "This summary reflects available vehicle evidence; it is not an independent airworthiness check."),

        T(Optional, "Naming",
            "Set the vehicle identifiers used for addressing and recognition.",
            "Connect the intended vehicle and read its current identifiers.|Choose a system ID that does not conflict with other vehicles on the link.|Apply and check the returned confirmation; reconnect if addressing changes.",
            "Verify the vehicle identity shown after reconnection. A local label and a flight-controller identifier are different things.",
            "If confirmation times out, reload before retrying because an earlier change may already have been saved."),
        T(Optional, "RTK/GPS Inject",
            "Forward correction data from a supported source to the connected vehicle.",
            "Select the correction source and review its connection settings.|Start the source and injection workflow, then monitor incoming and forwarded data.|Stop forwarding when the source is no longer intended for this vehicle.",
            "Check the vehicle's GPS status as well as correction traffic. Forwarded bytes alone do not prove an RTK solution.",
            "Check source compatibility and freshness; stale or unsuitable corrections do not improve a GPS fix."),
        T(Optional, "CubeID Update",
            "Inspect a local CubeID firmware image before a supported update workflow.",
            "Provide the path to the intended .bin image.|Run inspection and review file size, CRC32 and chunk count.|Confirm that the image is intended for the exact CubeID device.",
            "The displayed file summary confirms inspection only.",
            "The current page has no firmware-write command. Inspection does not flash the device or prove target compatibility."),
        T(Optional, "SiK Radio",
            "Read and configure a supported telemetry radio through a direct serial connection.",
            "Select the radio's serial port and connect/read the module.|Review local and remote link settings before changing them.|Use the explicit apply, save and reboot actions as required by the radio workflow.",
            "Reconnect and check both radio settings and the telemetry link.",
            "Close other applications using the same port. Incompatible settings on the two radios can break the link."),
        T(Optional, "CAN GPS Order",
            "Associate detected CAN GPS node identities with the intended GPS ordering.",
            "Identify each physical receiver and its reported node ID.|Review current ordering and any supported overrides.|Apply intentional changes and reboot if requested.",
            "After reconnecting, verify GPS instance identity and live status against the intended receiver.",
            "Do not assign ordering by guessing node IDs; parameter values alone do not show which physical receiver is connected."),
        T(Optional, "Battery Monitors",
            "Configure battery-monitor instances and calibrate voltage/current readings.",
            "Select the battery instance and monitor type that match the installed hardware.|Review capacity and associated thresholds.|Where calibration is supported, enter an independently measured reference and review the proposed correction before applying.",
            "Compare the live reading with the reference again, then check battery failsafe configuration.",
            "Use the correct units and instance. USB power alone may not provide a meaningful battery reading."),
        T(Optional, "DroneCAN / UAVCAN",
            "Review CAN bus settings and inspect nodes through a supported transport.",
            "Check bus wiring, termination and device power.|Select the supported connection and inspect reported nodes.|Review bus parameters and node settings before applying changes.",
            "Check that the intended nodes remain online and provide expected data after a restart.",
            "Vehicle CAN parameters are not proof of node presence. DroneCAN and other CAN protocols are not interchangeable."),
        T(Optional, "Joystick",
            "Configure a local joystick or gamepad and control whether its output is sent to the vehicle.",
            "Discover and select the input device.|Review axes, direction and neutral values before enabling vehicle output.|Use the explicit disable/release action when testing is complete.",
            "Verify neutral behaviour and the vehicle's response to losing or releasing joystick input.",
            "A detected controller does not mean vehicle output is enabled. Remove propellers for bench checks."),
        T(Optional, "Compass/Motor Calibration",
            "Review the compass motor-interference compensation workflow.",
            "Review compass setup and the operation's prerequisites.|Use the page's bounded start/stop controls only with the required safe test arrangement.|Inspect completion status and the reported compensation result.",
            "Confirm that the result was accepted and recheck compass behaviour afterward.",
            "The app's workflow requires propellers removed. A no-load bench run is not proof of acceptable magnetic interference under flight load; consult the vehicle-specific procedure."),
        T(Optional, "Rangefinder",
            "Configure the correct rangefinder instance, type, orientation and measurement limits.",
            "Match the selected instance to the sensor and its physical interface.|Review units, mounting direction and supported range.|Apply settings, reboot if requested, then refresh data.",
            "Compare reported distance with known targets within the sensor's valid range.",
            "A configured sensor can still have no valid reading. Check wiring, power and target conditions before changing limits."),
        T(Optional, "Airspeed",
            "Review airspeed sensor type, use and calibration settings.",
            "Identify the pressure sensor and check its pressure connections.|Configure only fields supported by the connected firmware.|Follow the sensor's calibration procedure and inspect the live reading.",
            "Check plausible zero and changing readings under controlled conditions before relying on airspeed.",
            "Do not enable airspeed use solely because parameters are present; check the actual sensor and vehicle requirements."),
        T(Optional, "PX4Flow",
            "Find guidance for a PX4FLOW optical-flow sensor.",
            "Use the Optical Flow section to review supported flow configuration.|Consult the PX4FLOW documentation for mounting, orientation and sensor setup.|Verify flow data and the required height source before relying on it.",
            "Check live sensor evidence and installation-specific requirements.",
            "The PX4Flow tab currently displays the Airspeed view. Its airspeed controls do not configure PX4FLOW; use Optical Flow or Parameters Editor instead.",
            "https://ardupilot.org/copter/docs/common-optical-flow-sensors-landingpage.html"),
        T(Optional, "Optical Flow",
            "Configure an optical-flow sensor for supported navigation workflows.",
            "Identify the sensor type and mounting orientation.|Review the flow settings and required range or height source.|Apply changes and follow the sensor-specific setup and validation procedure.",
            "Check valid flow and height data under suitable lighting and surface conditions.",
            "Optical flow uses visible ground features. Configuration alone does not establish reliable navigation.",
            "https://ardupilot.org/copter/docs/common-optical-flow-sensors-landingpage.html"),
        T(Optional, "OSD",
            "Open the central Onboard OSD editor for display layout and supported settings.",
            "Connect the intended vehicle and refresh its parameters.|Use Open Onboard OSD to reach Configuration's editor.|Select a screen, review layout changes and apply the selected screen there.",
            "Check the actual video/display output after applying; a local preview is not device readback.",
            "Available items and rendering depend on firmware and display hardware."),
        T(Optional, "Camera Gimbal",
            "Configure camera and mount parameters for the installed payload.",
            "Identify the camera/gimbal type and connection.|Review mount functions, control assignments and supported options.|Apply settings and use Payload Control for live operation.",
            "Check pointing direction and mechanical travel with the payload clear of obstructions.",
            "This setup section configures parameters; live camera and gimbal operation belongs in Payload Control."),
        T(Optional, "Motor Test",
            "Check physical motor order, direction and proposed spin thresholds.",
            "Remove all propellers and confirm the displayed frame.|Choose a short duration and appropriate low test output; test one position at a time against the motor-order diagram.|Review spin-threshold calculations and use the dedicated Set action to write a proposed value.",
            "Check the actual motor that turns, its direction and the confirmed value after a write. Keep STOP All Motors accessible.",
            "The top view shows expected geometry, nose direction, test letter, logical motor and configured SERVO assignment. These are separate identities: BetaFlightX uses A to Motor 2, B to Motor 1, C to Motor 3 and D to Motor 4. Missing or ambiguous outputs require review. The diagram does not verify physical wiring. Do not use spin-threshold offsets as universal recommendations.",
            "https://ardupilot.org/copter/docs/connect-escs-and-motors.html#motor-order-diagrams"),
        T(Optional, "Bluetooth Setup",
            "Configure a supported Bluetooth serial module directly.",
            "Select the module's serial port and probe/read it.|Review supported identity and communication settings.|Apply deliberate changes and reconnect using the resulting settings.",
            "Verify communication through the module after configuration.",
            "A vehicle telemetry connection does not identify the external Bluetooth module. Release the serial port from other tools first."),
        T(Optional, "Parachute",
            "Review parachute enablement and release configuration.",
            "Identify the release mechanism and follow its manufacturer's safe setup procedure.|Keep the release mechanism made safe while reviewing parameters.|Apply supported settings and use the documented verification procedure.",
            "Verify configuration, wiring and release conditions independently.",
            "This page does not deploy the parachute. Ejection can be hazardous; parameter confirmation is not a deployment test.",
            "https://ardupilot.org/copter/docs/common-parachute.html"),
        T(Optional, "ESP8266",
            "Validate Wi-Fi settings intended for an ESP8266 bridge.",
            "Enter settings for the intended component.|Run validation and correct reported input errors.|Use a supported device-configuration workflow to actually transfer settings.",
            "Check the bridge connection independently after configuring the device.",
            "Validation on this page does not prove that credentials or other settings were written to hardware."),
        T(Optional, "Antenna Tracker",
            "Review tracker configuration and target information.",
            "Connect the intended tracker and inspect available identity and target status.|Review supported tracker parameters in Parameters Editor.|Check mechanical limits and the tracker-specific setup documentation.",
            "Confirm that target information is current and belongs to the intended vehicle.",
            "Actuator testing is currently unavailable on this page; it must not be treated as a completed pointing test."),
        T(Optional, "FFT",
            "Analyse an existing sample export to inspect vibration-frequency content.",
            "Obtain a suitable exported DataFlash sample set.|Supply the samples and their correct sample rate, then run the analysis.|Review the spectrum and reported peak alongside the operating conditions recorded in the log.",
            "Check sample spacing, units and whether the data represents the condition being investigated.",
            "This tool does not download logs or automatically choose safe filter settings. An isolated spectral peak is not a complete tuning diagnosis."),

        T(Configuration, "GeoFence",
            "Edit supported inclusion/exclusion areas, return points and fence parameters.",
            "Download the current fence and retain a backup.|Create or edit areas, finish polygons and review map geometry.|Validate and upload, then download again to check the vehicle copy.",
            "Review enablement and breach actions as well as geometry. Local edits do not change the vehicle until uploaded.",
            "Clear vehicle removes the stored fence. Check altitude references and firmware support before relying on a fence."),
        T(Configuration, "Basic Tuning",
            "Edit the commonly used tuning fields presented for the connected vehicle.",
            "Refresh the relevant group and save a reference copy.|Change a small, understood set of fields using their displayed units.|Apply the group and review confirmed values; use Revert to discard pending edits.",
            "Check required reboots and assess the change using the appropriate controlled test and logs.",
            "Import/export covers the presented fields, not necessarily every vehicle parameter. Do not copy tuning from an unrelated airframe."),
        T(Configuration, "Extended Tuning",
            "Review advanced tuning groups and explicitly preview axis-to-axis copies.",
            "Refresh the group and identify the control loop and units.|Edit values or preview an axis copy and review its proposed changes.|Confirm a copy into pending values, then separately review and apply the group.",
            "Check readback and assess behaviour from appropriate tests and logs.",
            "Confirming a preview is not the same as writing it. Different axes may need different tuning."),
        T(Configuration, "Onboard OSD",
            "Edit supported onboard display screens and item placement.",
            "Refresh the connected vehicle's OSD configuration.|Select a screen and review item visibility and position in the preview.|Apply the selected screen; import/export layouts when you need a reusable local copy.",
            "Check the physical display and confirmed vehicle values after applying changes.",
            "The preview depends on available metadata and is not proof of what a particular display renders."),
        T(Configuration, "Mavlink Ftp",
            "Browse and transfer files exposed by the vehicle's MAVLink FTP service, including remote modification dates when supported.",
            "Connect a supported vehicle and open Configuration > Mavlink Ftp, then refresh the remote listing.|Review Name, Type and Size to identify the intended file or directory. Modified (local) shows the remote modification timestamp converted to your computer's local time.|Navigate to the intended path before starting a transfer or other file operation.|Wait for the operation report, then refresh the listing or inspect the resulting local file.",
            "Check filenames, sizes and completion status as well as dates. A modification timestamp describes the remote file; it does not confirm transfer completion or identify the start of a recorded flight. An interrupted transfer should not be assumed complete.",
            "The app automatically falls back to ordinary listings on older firmware. Missing or unsupported modification dates remain blank; a blank date is not an error by itself. MAVLink FTP uses the telemetry connection and does not mount a USB drive. Remote file changes are separate from parameter writes; keep a backup before replacing or removing important files."),
        T(Configuration, "Parameters Editor",
            "Search, review, save/load and apply vehicle parameters, including pasted text edits.",
            "Load the intended vehicle's parameters and save a backup.|Find values in the grid or open the text editor and enter one name/value pair per line.|Use Apply modified to write reviewed changes, then read the Markdown progress and completion report.",
            "Check confirmed changes, skipped unknown names, invalid values and write failures separately. Baseline is the first received value in the current vehicle/firmware editing session, not a factory default. Refresh retains it; a new session after disconnect or vehicle change captures a new baseline. Hover its value for current FC value and any explicit metadata default; unavailable defaults remain Unknown. Reboot when the report requires it.",
            "The text editor accepts full-line and inline // comments and supported separators such as =. Invalid or unknown entries are reported rather than silently treated as successful writes. Open Parameter profiles from the parameter actions menu to create a named set from all current values, modified values or a comma/space-separated list of selected names. Snapshots include pending edits. Add a description and comma-separated tags, then Create new profile. Select a saved profile to review firmware/vehicle mismatch warnings and live/profile values; select compatible differences and Stage selected. Close profiles and use Apply modified only after reviewing the pending edits. Save details renames or updates metadata without replacing stored values; Duplicate creates a separate copy. Profiles also support confirmed deletion and JSON import/export; importing creates a new local profile and never overwrites an existing one."),
        T(Configuration, "CubeLan 8 Port Switch",
            "Read and edit the supported CubeLAN switch settings.",
            "Use Discover / read to obtain the current device configuration.|Review COS, COS priority, EEE, VLAN tagging and the membership matrix.|Export a backup, then use Apply and verify for the intended changes; Revert discards local edits.",
            "Check the verification result and network connectivity after applying.",
            "This editor does not expose PoE, port enablement, VLAN IDs, modes, authentication or editable labels. Do not infer unsupported settings from the displayed matrix.")
    ];

    private static SectionHelp T(string group, string title, string purpose, string steps,
        string verify, string note, string? url = null) =>
        new(group, title, purpose, steps.Split('|'), verify, note,
            new Uri(url ?? (group == Mandatory ? SetupDocs : group == Configuration
                ? "https://ardupilot.org/planner/docs/mission-planner-configuration-and-tuning.html"
                : PeripheralDocs)));

    public static UserDocument CreateDocument(SectionHelp topic)
    {
        var builder = new UserDocumentBuilder().Heading(topic.Title)
            .Paragraph(topic.Group + " / " + topic.Title)
            .Paragraph(topic.Purpose)
            .Heading("How to use this section", 3);
        foreach (var step in topic.Steps) builder.Bullet(step);
        builder.Heading("Verify the result", 3).Paragraph(topic.Verification)
            .Heading("Important details", 3).Note(topic.Note);
        if (topic.Group is Mandatory or Optional)
            builder.Paragraph("Available controls depend on the connected firmware and hardware. Refresh after reconnecting; a missing or disabled control is not evidence that a setting has been applied.");
        else if (topic.Group == Configuration)
            builder.Paragraph("Keep a backup before changing configuration. Editing or loading values locally is separate from applying them to the connected vehicle.");
        return builder.Build(topic.Title);
    }
}

public sealed record SectionHelp(string Group, string Title, string Purpose, string[] Steps,
    string Verification, string Note, Uri Documentation);
