namespace MissionPlanner.App.Presentation.Documents;

/// <summary>Offline, task-oriented help for every visible hardware and configuration section.</summary>
public static class SectionHelpCatalog
{
    private const string Mandatory = "Mandatory Hardware";
    private const string Optional = "Optional Hardware";
    private const string Configuration = "Configuration";
    private const string SetupDocs = "https://ardupilot.org/copter/docs/configuring-hardware.html";
    private const string PeripheralDocs = "https://ardupilot.org/copter/docs/common-optional-hardware.html";

    public static IReadOnlyList<SectionHelp> Sections { get; } =
    [
        T(Mandatory, "Frame",
            "Select the vehicle frame class and geometry so the flight controller uses the appropriate motor layout.",
            "Identify the physical frame and controller orientation.|Review the supported frame choices and apply the matching selection.|Complete any requested reboot, then use Motor Test to check each motor against the motor-order diagram.",
            "Check the frame reported by the vehicle after reconnecting. A matching motor count alone does not establish the correct geometry.",
            "Remove propellers before checking motor order. Do not copy another vehicle's frame settings without checking its geometry."),
        T(Mandatory, "Accel Calibration",
            "Calibrate accelerometer offsets and establish the controller's orientation and level reference.",
            "Place the disarmed vehicle on a stable surface with propellers removed.|Check board orientation, then start calibration and follow each requested position.|Keep the vehicle still for each measurement and wait for the completion message.",
            "Return the vehicle to level and check that the attitude display agrees with its actual orientation.",
            "If a position fails, check movement and orientation before repeating calibration; do not compensate for incorrect mounting with arbitrary trim."),
        T(Mandatory, "Compass",
            "Identify and calibrate the compasses used for heading estimation.",
            "Review detected devices, orientation and priority before starting.|Move away from magnetic objects and high-current wiring, then follow the calibration prompts.|Review the result for each compass and complete any requested reboot.",
            "Check that heading changes consistently when the vehicle turns. Recheck device identity after replacing a GPS/compass unit.",
            "A successful calibration does not prove that motor interference is acceptable."),
        T(Mandatory, "Radio Calibration",
            "Capture receiver channel endpoints and verify stick mapping.",
            "Turn on the transmitter, connect the receiver and remove propellers.|Check channel movement, then run the capture workflow and move the requested controls through their full range.|Review endpoints, centre positions and channel mapping before confirming.",
            "Move each stick independently and verify direction, range and neutral position. Check flight-mode switches separately.",
            "Keep trims and transmitter configuration consistent with the calibration. Verify receiver-loss behaviour in Failsafe."),
        T(Mandatory, "Servo Output",
            "Assign functions to output channels and review reversal, trim and output limits.",
            "Match physical wiring to controller output labels.|Review each channel's function and supported limits, then apply only the intended changes.|Use an appropriate bounded test to verify movement after configuration.",
            "Check direction and mechanical travel without binding. A function number does not identify what is physically connected.",
            "Remove propellers and keep mechanisms clear. Do not assume a serial, CAN or timer-group output behaves like an ordinary PWM servo."),
        T(Mandatory, "Serial Ports",
            "Configure the protocol, baud rate and options used by each controller serial port.",
            "Consult the board wiring documentation to map SERIAL indices to connectors.|Select settings required by the attached peripheral and review pending changes.|Apply, reboot when required, and reconnect before checking the peripheral.",
            "Look for actual device data rather than treating a stored protocol value as proof of communication.",
            "Changing the port carrying telemetry can disconnect the app. Record the original settings and a recovery connection first."),
        T(Mandatory, "ESC Calibration",
            "Review motor output configuration and the calibration workflow appropriate to the ESC protocol.",
            "Identify the ESC model, protocol and supported controller outputs.|Read the workflow instructions before starting any calibration or power-cycle sequence.|After completion, verify output configuration and use short Motor Test commands.",
            "Check that the expected motors respond consistently and stop correctly.",
            "Remove all propellers. ESC calibration requirements depend on the protocol; do not apply a PWM calibration sequence to every ESC type.",
            "https://ardupilot.org/copter/docs/common-escs-and-motors.html"),
        T(Mandatory, "Flight Modes",
            "Assign supported flight modes to the receiver's mode-switch positions.",
            "Confirm the selected mode channel and its live receiver input.|Choose a suitable mode for each switch position and apply the changes.|With the vehicle disarmed, move the switch through every position.",
            "Check the vehicle's reported mode, not just the selected label in the editor. Check prerequisites for navigation-dependent modes.",
            "Keep a familiar recovery mode accessible and verify failsafe actions independently."),
        T(Mandatory, "Failsafe",
            "Review actions for loss of radio, telemetry, battery reserve and other supported failure conditions.",
            "Read the descriptions for the connected firmware and vehicle type.|Choose thresholds and actions appropriate to the battery, navigation capability and operating area.|Apply changes, read them back, then follow the documented disarmed test procedure.",
            "Check the observed failsafe indication and resulting action. A threshold saved in the editor is not a functional test.",
            "Do not disable a failsafe simply to clear a warning. Several failsafe conditions may occur together."),
        T(Mandatory, "Initial Tune Params",
            "Review the initial filter, acceleration and motor settings used before detailed flight tuning.",
            "Complete frame, sensor, radio and motor setup first.|Review the available fields and their units against the actual vehicle.|Apply a small reviewed set of changes and retain a known-good parameter backup.",
            "Check confirmed values and required reboots before proceeding to the firmware's first-flight and tuning procedure.",
            "Values are not universal across airframes. This page does not establish that a vehicle is ready to fly."),
        T(Mandatory, "Hardware ID",
            "Inspect board and sensor identifiers for troubleshooting and comparison.",
            "Connect the intended vehicle and refresh its identification data.|Record the reported identifiers before changing or replacing hardware.|Compare the results with the board documentation and the device you intended to connect.",
            "If identifiers are missing, check the connection and firmware support before drawing conclusions.",
            "An identifier is diagnostic evidence; it does not prove sensor health, wiring correctness or exact firmware compatibility."),
        T(Mandatory, "ADSB",
            "Review supported ADS-B receiver or transponder settings.",
            "Identify the installed device and its connection requirements.|Review available configuration and device-specific identifiers before applying changes.|Check that traffic or device status is actually received.",
            "Distinguish receiver data from transponder configuration and verify the selected device instance.",
            "Parameter availability does not prove an ADS-B device is attached. Use the device documentation for identifiers and operating requirements."),
        T(Mandatory, "Safety",
            "Review safety-switch, arming and related protective settings exposed for the current vehicle.",
            "Read the current state and any reported arming failures.|Resolve the underlying setup or sensor issue before editing safety settings.|Apply intentional changes and verify the safety switch and arming indications while disarmed.",
            "Confirm which outputs remain inhibited and which checks still apply after any required reboot.",
            "Do not treat clearing a warning by disabling a check as a repair."),
        T(Mandatory, "Summary",
            "Review setup status and identify remaining configuration work.",
            "Refresh after completing calibration or parameter changes.|Read each reported item and return to its setup section where further work is needed.|Recheck the summary after required reboots and reconnection.",
            "Distinguish confirmed values, missing information and unresolved warnings. Verify physical wiring and movement separately.",
            "This summary reflects available vehicle evidence; it is not an independent airworthiness check."),

        T(Optional, "Naming",
            "Set the vehicle identifiers used for addressing and recognition.",
            "Connect the intended vehicle and read its current identifiers.|Choose a system ID that does not conflict with other vehicles on the link.|Apply and check the returned confirmation; reconnect if addressing changes.",
            "Verify the vehicle identity shown after reconnection. A local label and a flight-controller identifier are different things.",
            "If confirmation times out, reload before retrying because an earlier change may already have been saved."),
        T(Optional, "RTK/GPS Inject",
            "Forward correction data from a supported source to the connected vehicle.",
            "Select the correction source and review its connection settings.|Start the source and injection workflow, then monitor incoming and forwarded data.|Stop forwarding when the source is no longer intended for this vehicle.",
            "Check the vehicle's GPS status as well as correction traffic. Forwarded bytes alone do not prove an RTK solution.",
            "Check source compatibility and freshness; stale or unsuitable corrections do not improve a GPS fix."),
        T(Optional, "CubeID Update",
            "Inspect a local CubeID firmware image before a supported update workflow.",
            "Provide the path to the intended .bin image.|Run inspection and review file size, CRC32 and chunk count.|Confirm that the image is intended for the exact CubeID device.",
            "The displayed file summary confirms inspection only.",
            "The current page has no firmware-write command. Inspection does not flash the device or prove target compatibility."),
        T(Optional, "SiK Radio",
            "Read and configure a supported telemetry radio through a direct serial connection.",
            "Select the radio's serial port and connect/read the module.|Review local and remote link settings before changing them.|Use the explicit apply, save and reboot actions as required by the radio workflow.",
            "Reconnect and check both radio settings and the telemetry link.",
            "Close other applications using the same port. Incompatible settings on the two radios can break the link."),
        T(Optional, "CAN GPS Order",
            "Associate detected CAN GPS node identities with the intended GPS ordering.",
            "Identify each physical receiver and its reported node ID.|Review current ordering and any supported overrides.|Apply intentional changes and reboot if requested.",
            "After reconnecting, verify GPS instance identity and live status against the intended receiver.",
            "Do not assign ordering by guessing node IDs; parameter values alone do not show which physical receiver is connected."),
        T(Optional, "Battery Monitors",
            "Configure battery-monitor instances and calibrate voltage/current readings.",
            "Select the battery instance and monitor type that match the installed hardware.|Review capacity and associated thresholds.|Where calibration is supported, enter an independently measured reference and review the proposed correction before applying.",
            "Compare the live reading with the reference again, then check battery failsafe configuration.",
            "Use the correct units and instance. USB power alone may not provide a meaningful battery reading."),
        T(Optional, "DroneCAN / UAVCAN",
            "Review CAN bus settings and inspect nodes through a supported transport.",
            "Check bus wiring, termination and device power.|Select the supported connection and inspect reported nodes.|Review bus parameters and node settings before applying changes.",
            "Check that the intended nodes remain online and provide expected data after a restart.",
            "Vehicle CAN parameters are not proof of node presence. DroneCAN and other CAN protocols are not interchangeable."),
        T(Optional, "Joystick",
            "Configure a local joystick or gamepad and control whether its output is sent to the vehicle.",
            "Discover and select the input device.|Review axes, direction and neutral values before enabling vehicle output.|Use the explicit disable/release action when testing is complete.",
            "Verify neutral behaviour and the vehicle's response to losing or releasing joystick input.",
            "A detected controller does not mean vehicle output is enabled. Remove propellers for bench checks."),
        T(Optional, "Compass/Motor Calibration",
            "Review the compass motor-interference compensation workflow.",
            "Review compass setup and the operation's prerequisites.|Use the page's bounded start/stop controls only with the required safe test arrangement.|Inspect completion status and the reported compensation result.",
            "Confirm that the result was accepted and recheck compass behaviour afterward.",
            "The app's workflow requires propellers removed. A no-load bench run is not proof of acceptable magnetic interference under flight load; consult the vehicle-specific procedure."),
        T(Optional, "Rangefinder",
            "Configure the correct rangefinder instance, type, orientation and measurement limits.",
            "Match the selected instance to the sensor and its physical interface.|Review units, mounting direction and supported range.|Apply settings, reboot if requested, then refresh data.",
            "Compare reported distance with known targets within the sensor's valid range.",
            "A configured sensor can still have no valid reading. Check wiring, power and target conditions before changing limits."),
        T(Optional, "Airspeed",
            "Review airspeed sensor type, use and calibration settings.",
            "Identify the pressure sensor and check its pressure connections.|Configure only fields supported by the connected firmware.|Follow the sensor's calibration procedure and inspect the live reading.",
            "Check plausible zero and changing readings under controlled conditions before relying on airspeed.",
            "Do not enable airspeed use solely because parameters are present; check the actual sensor and vehicle requirements."),
        T(Optional, "PX4Flow",
            "Find guidance for a PX4FLOW optical-flow sensor.",
            "Use the Optical Flow section to review supported flow configuration.|Consult the PX4FLOW documentation for mounting, orientation and sensor setup.|Verify flow data and the required height source before relying on it.",
            "Check live sensor evidence and installation-specific requirements.",
            "The PX4Flow tab currently displays the Airspeed view. Its airspeed controls do not configure PX4FLOW; use Optical Flow or Parameters Editor instead.",
            "https://ardupilot.org/copter/docs/common-optical-flow-sensors-landingpage.html"),
        T(Optional, "Optical Flow",
            "Configure an optical-flow sensor for supported navigation workflows.",
            "Identify the sensor type and mounting orientation.|Review the flow settings and required range or height source.|Apply changes and follow the sensor-specific setup and validation procedure.",
            "Check valid flow and height data under suitable lighting and surface conditions.",
            "Optical flow uses visible ground features. Configuration alone does not establish reliable navigation.",
            "https://ardupilot.org/copter/docs/common-optical-flow-sensors-landingpage.html"),
        T(Optional, "OSD",
            "Open the central Onboard OSD editor for display layout and supported settings.",
            "Connect the intended vehicle and refresh its parameters.|Use Open Onboard OSD to reach Configuration's editor.|Select a screen, review layout changes and apply the selected screen there.",
            "Check the actual video/display output after applying; a local preview is not device readback.",
            "Available items and rendering depend on firmware and display hardware."),
        T(Optional, "Camera Gimbal",
            "Configure camera and mount parameters for the installed payload.",
            "Identify the camera/gimbal type and connection.|Review mount functions, control assignments and supported options.|Apply settings and use Payload Control for live operation.",
            "Check pointing direction and mechanical travel with the payload clear of obstructions.",
            "This setup section configures parameters; live camera and gimbal operation belongs in Payload Control."),
        T(Optional, "Motor Test",
            "Check physical motor order, direction and proposed spin thresholds.",
            "Remove all propellers and confirm the displayed frame.|Choose a short duration and appropriate low test output; test one position at a time against the motor-order diagram.|Review spin-threshold calculations and use the dedicated Set action to write a proposed value.",
            "Check the actual motor that turns, its direction and the confirmed value after a write. Keep STOP All Motors accessible.",
            "A test label identifies the requested motor, not the wiring. Do not use spin-threshold offsets as universal recommendations.",
            "https://ardupilot.org/copter/docs/connect-escs-and-motors.html#motor-order-diagrams"),
        T(Optional, "Bluetooth Setup",
            "Configure a supported Bluetooth serial module directly.",
            "Select the module's serial port and probe/read it.|Review supported identity and communication settings.|Apply deliberate changes and reconnect using the resulting settings.",
            "Verify communication through the module after configuration.",
            "A vehicle telemetry connection does not identify the external Bluetooth module. Release the serial port from other tools first."),
        T(Optional, "Parachute",
            "Review parachute enablement and release configuration.",
            "Identify the release mechanism and follow its manufacturer's safe setup procedure.|Keep the release mechanism made safe while reviewing parameters.|Apply supported settings and use the documented verification procedure.",
            "Verify configuration, wiring and release conditions independently.",
            "This page does not deploy the parachute. Ejection can be hazardous; parameter confirmation is not a deployment test.",
            "https://ardupilot.org/copter/docs/common-parachute.html"),
        T(Optional, "ESP8266",
            "Validate Wi-Fi settings intended for an ESP8266 bridge.",
            "Enter settings for the intended component.|Run validation and correct reported input errors.|Use a supported device-configuration workflow to actually transfer settings.",
            "Check the bridge connection independently after configuring the device.",
            "Validation on this page does not prove that credentials or other settings were written to hardware."),
        T(Optional, "Antenna Tracker",
            "Review tracker configuration and target information.",
            "Connect the intended tracker and inspect available identity and target status.|Review supported tracker parameters in Parameters Editor.|Check mechanical limits and the tracker-specific setup documentation.",
            "Confirm that target information is current and belongs to the intended vehicle.",
            "Actuator testing is currently unavailable on this page; it must not be treated as a completed pointing test."),
        T(Optional, "FFT",
            "Analyse an existing sample export to inspect vibration-frequency content.",
            "Obtain a suitable exported DataFlash sample set.|Supply the samples and their correct sample rate, then run the analysis.|Review the spectrum and reported peak alongside the operating conditions recorded in the log.",
            "Check sample spacing, units and whether the data represents the condition being investigated.",
            "This tool does not download logs or automatically choose safe filter settings. An isolated spectral peak is not a complete tuning diagnosis."),

        T(Configuration, "GeoFence",
            "Edit supported inclusion/exclusion areas, return points and fence parameters.",
            "Download the current fence and retain a backup.|Create or edit areas, finish polygons and review map geometry.|Validate and upload, then download again to check the vehicle copy.",
            "Review enablement and breach actions as well as geometry. Local edits do not change the vehicle until uploaded.",
            "Clear vehicle removes the stored fence. Check altitude references and firmware support before relying on a fence."),
        T(Configuration, "Basic Tuning",
            "Edit the commonly used tuning fields presented for the connected vehicle.",
            "Refresh the relevant group and save a reference copy.|Change a small, understood set of fields using their displayed units.|Apply the group and review confirmed values; use Revert to discard pending edits.",
            "Check required reboots and assess the change using the appropriate controlled test and logs.",
            "Import/export covers the presented fields, not necessarily every vehicle parameter. Do not copy tuning from an unrelated airframe."),
        T(Configuration, "Extended Tuning",
            "Review advanced tuning groups and explicitly preview axis-to-axis copies.",
            "Refresh the group and identify the control loop and units.|Edit values or preview an axis copy and review its proposed changes.|Confirm a copy into pending values, then separately review and apply the group.",
            "Check readback and assess behaviour from appropriate tests and logs.",
            "Confirming a preview is not the same as writing it. Different axes may need different tuning."),
        T(Configuration, "Onboard OSD",
            "Edit supported onboard display screens and item placement.",
            "Refresh the connected vehicle's OSD configuration.|Select a screen and review item visibility and position in the preview.|Apply the selected screen; import/export layouts when you need a reusable local copy.",
            "Check the physical display and confirmed vehicle values after applying changes.",
            "The preview depends on available metadata and is not proof of what a particular display renders."),
        T(Configuration, "Mavlink Ftp",
            "Browse and transfer files exposed by the vehicle's MAVLink FTP service.",
            "Connect a supported vehicle and refresh the remote listing.|Select the intended path before a transfer or other file operation.|Wait for the operation report and inspect the resulting listing or local file.",
            "Check filenames, sizes and completion status. An interrupted transfer should not be assumed complete.",
            "Remote file changes are separate from parameter writes. Keep a backup before replacing or removing important files."),
        T(Configuration, "Parameters Editor",
            "Search, review, save/load and apply vehicle parameters, including pasted text edits.",
            "Load the intended vehicle's parameters and save a backup.|Find values in the grid or open the text editor and enter one name/value pair per line.|Use Apply modified to write reviewed changes, then read the Markdown progress and completion report.",
            "Check confirmed changes, skipped unknown names, invalid values and write failures separately. Reboot when the report requires it.",
            "The text editor accepts full-line and inline // comments and supported separators such as =. Invalid or unknown entries are reported rather than silently treated as successful writes."),
        T(Configuration, "CubeLan 8 Port Switch",
            "Read and edit the supported CubeLAN switch settings.",
            "Use Discover / read to obtain the current device configuration.|Review COS, COS priority, EEE, VLAN tagging and the membership matrix.|Export a backup, then use Apply and verify for the intended changes; Revert discards local edits.",
            "Check the verification result and network connectivity after applying.",
            "This editor does not expose PoE, port enablement, VLAN IDs, modes, authentication or editable labels. Do not infer unsupported settings from the displayed matrix.")
    ];

    private static SectionHelp T(string group, string title, string purpose, string steps,
        string verify, string note, string? url = null) =>
        new(group, title, purpose, steps.Split('|'), verify, note,
            new Uri(url ?? (group == Mandatory ? SetupDocs : group == Configuration
                ? "https://ardupilot.org/planner/docs/mission-planner-configuration-and-tuning.html"
                : PeripheralDocs)));

    public static UserDocument CreateDocument(SectionHelp topic)
    {
        var builder = new UserDocumentBuilder().Heading(topic.Title)
            .Paragraph(topic.Group + " / " + topic.Title)
            .Paragraph(topic.Purpose)
            .Heading("How to use this section", 3);
        foreach (var step in topic.Steps) builder.Bullet(step);
        builder.Heading("Verify the result", 3).Paragraph(topic.Verification)
            .Heading("Important details", 3).Note(topic.Note);
        if (topic.Group != Configuration)
            builder.Paragraph("Available controls depend on the connected firmware and hardware. Refresh after reconnecting; a missing or disabled control is not evidence that a setting has been applied.");
        else
            builder.Paragraph("Keep a backup before changing configuration. Editing or loading values locally is separate from applying them to the connected vehicle.");
        return builder.Build(topic.Title);
    }
}

public sealed record SectionHelp(string Group, string Title, string Purpose, string[] Steps,
    string Verification, string Note, Uri Documentation);
