<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MissionPlanner.Firmware\MissionPlanner.Firmware.csproj" />
    <ProjectReference Include="..\MissionPlanner.Shared.Models\MissionPlanner.Shared.Models.csproj" />
    <ProjectReference Include="..\MissionPlanner.Transport\MissionPlanner.Transport.csproj" />
    <ProjectReference Include="..\MissionPlanner.MavLink\MissionPlanner.MavLink.csproj" />
    <ProjectReference Include="..\MissionPlanner.Simulation\MissionPlanner.Simulation.csproj" />
  </ItemGroup>

</Project>
