using System.Globalization;
using System.Net;
using System.Text;

namespace MissionPlanner.MavLink.Generator;

/// <summary>
/// Emits deterministic C# protocol enums from resolved MAVLink XML enums.
/// </summary>
public static class MavLinkEnumSourceGenerator
{
    /// <summary>
    /// Generates the protocol enum source file.
    /// </summary>
    /// <param name="definitions">The resolved enum definitions.</param>
    /// <param name="sourceRevision">The pinned MAVLink source revision.</param>
    /// <returns>The generated C# source.</returns>
    public static string Generate(IReadOnlyCollection<DialectEnumDefinition> definitions, string sourceRevision)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("// Generated from the official ardupilotmega.xml dialect and its transitive includes.");
        source.Append("// MAVLink source revision: ").AppendLine(sourceRevision);
        source.AppendLine("// DO NOT EDIT MANUALLY. Regenerate with MissionPlanner.MavLink.Generator.");
        source.AppendLine();
        source.AppendLine("namespace MissionPlanner.MavLink.Generated;");

        foreach (var definition in definitions.OrderBy(definition => definition.Name, StringComparer.Ordinal))
        {
            source.AppendLine();
            AppendSummary(source, definition.Description, $"Defines MAVLink {definition.Name} values.");
            if (definition.IsBitmask)
            {
                source.AppendLine("[Flags]");
            }

            var typeName = ToIdentifier(definition.Name);
            source.Append("public enum ").Append(typeName).Append(" : ").AppendLine(definition.UnderlyingType);
            source.AppendLine("{");
            var memberNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (var entry in definition.Entries)
            {
                AppendSummary(source, entry.Description, $"Represents {entry.Name}.", "    ");
                var memberName = ToMemberName(definition.Name, entry.Name);
                if (!memberNames.Add(memberName))
                {
                    memberName += "Value" + entry.Value.ToString(CultureInfo.InvariantCulture);
                    if (!memberNames.Add(memberName))
                    {
                        throw new InvalidDataException($"Enum {definition.Name} contains an irreducible C# member-name collision for {entry.Name}.");
                    }
                }

                source.Append("    ").Append(memberName).Append(" = ")
                    .Append(FormatValue(entry.Value, definition.UnderlyingType)).AppendLine(",");
            }

            source.AppendLine("}");
        }

        return source.ToString();
    }

    /// <summary>
    /// Converts an XML enum name to its generated C# type name.
    /// </summary>
    /// <param name="value">The XML identifier.</param>
    /// <returns>The C# identifier.</returns>
    public static string ToIdentifier(string value)
    {
        var identifier = string.Concat(value.Split('_', StringSplitOptions.RemoveEmptyEntries).Select(ToWord));
        return identifier.Length > 0 && char.IsDigit(identifier[0]) ? "Value" + identifier : identifier;
    }

    private static string ToMemberName(string enumName, string entryName)
    {
        var prefix = enumName switch
        {
            "MAV_COMPONENT" => "MAV_COMP_ID_",
            "MAV_MISSION_RESULT" => "MAV_MISSION_",
            _ => enumName + "_"
        };
        var suffix = entryName.StartsWith(prefix, StringComparison.Ordinal) ? entryName[prefix.Length..] : entryName;
        return ToIdentifier(suffix);
    }

    private static string ToWord(string word)
    {
        if (word.Length == 0)
        {
            return string.Empty;
        }

        if (word.Equals("ARDUPILOTMEGA", StringComparison.Ordinal))
        {
            return "ArduPilotMega";
        }

        if (word.Equals("MISSIONPLANNER", StringComparison.Ordinal))
        {
            return "MissionPlanner";
        }

        var lower = word.ToLowerInvariant();
        return char.ToUpperInvariant(lower[0]) + lower[1..];
    }

    private static string FormatValue(ulong value, string underlyingType) => underlyingType switch
    {
        "uint" when value > int.MaxValue => value.ToString(CultureInfo.InvariantCulture) + "u",
        "ulong" => value.ToString(CultureInfo.InvariantCulture) + "UL",
        _ => value.ToString(CultureInfo.InvariantCulture)
    };

    private static void AppendSummary(StringBuilder source, string description, string fallback, string indent = "")
    {
        source.Append(indent).AppendLine("/// <summary>");
        source.Append(indent).Append("/// ").AppendLine(WebUtility.HtmlEncode(string.IsNullOrWhiteSpace(description) ? fallback : description));
        source.Append(indent).AppendLine("/// </summary>");
    }
}
