using System.Globalization;
using System.Text;

namespace MissionPlanner.MavLink.Generator;

/// <summary>
/// Emits deterministic C# registry data from resolved MAVLink dialect definitions.
/// </summary>
public static class MavLinkRegistrySourceGenerator
{
    /// <summary>
    /// Generates the registry source file.
    /// </summary>
    /// <param name="definitions">The resolved dialect definitions.</param>
    /// <param name="sourceRevision">The pinned MAVLink source revision.</param>
    /// <returns>The generated C# source.</returns>
    public static string Generate(
        IReadOnlyCollection<DialectMessageDefinition> definitions,
        string sourceRevision)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("// Generated from the official ardupilotmega.xml dialect and its transitive includes.");
        source.Append("// MAVLink source revision: ").AppendLine(sourceRevision);
        source.AppendLine("// DO NOT EDIT MANUALLY. Regenerate with MissionPlanner.MavLink.Generator.");
        source.AppendLine();
        source.AppendLine("using MissionPlanner.MavLink.Messages;");
        source.AppendLine();
        source.AppendLine("namespace MissionPlanner.MavLink.Generated;");
        source.AppendLine();
        source.AppendLine("internal static class GeneratedMavLinkMessageDefinitions");
        source.AppendLine("{");
        source.AppendLine("    internal static readonly MavLinkMessageDefinition[] All =");
        source.AppendLine("    [");
        foreach (var definition in definitions.OrderBy(definition => definition.MessageId))
        {
            source.Append("        new(")
                .Append(definition.MessageId.ToString(CultureInfo.InvariantCulture)).Append("u, \"")
                .Append(Escape(definition.Name)).Append("\", ")
                .Append(definition.CrcExtra.ToString(CultureInfo.InvariantCulture)).Append(", ")
                .Append(definition.MinimumPayloadLength.ToString(CultureInfo.InvariantCulture)).Append(", ")
                .Append(definition.MaximumPayloadLength.ToString(CultureInfo.InvariantCulture)).Append(", \"")
                .Append(Escape(definition.Dialect)).Append("\", ")
                .Append(definition.IsDeprecated ? "true" : "false")
                .AppendLine("),");
        }

        source.AppendLine("    ];");
        source.AppendLine("}");
        return source.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal);
}
