<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>MissionPlanner.App</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Resources\Assets\**" />
        <AvaloniaResource Include="Introduction\**" />
	</ItemGroup>

	<ItemGroup>
	  <AvaloniaResource Include="Resources\AppIcon\mpdesktop.png" />
	  <AvaloniaResource Include="Resources\AppIcon\mpdesktop.svg" />
	  <AvaloniaResource Include="Resources\Images\ardupilot.png" />
	  <AvaloniaResource Include="Resources\Images\light_connect_icon.png" />
	  <AvaloniaResource Include="Resources\Images\light_disconnect_icon.png" />
	  <AvaloniaResource Include="Resources\Images\light_help_icon.png" />
	  <AvaloniaResource Include="Resources\Images\light_initialsetup_icon.png" />
	  <AvaloniaResource Include="Resources\Images\light_simulation_icon.png" />
	  <AvaloniaResource Include="Resources\Images\light_terminal_icon.png" />
	  <AvaloniaResource Include="Resources\Images\01_01.png" />
	  <AvaloniaResource Include="Resources\Images\01_03.png" />
	  <AvaloniaResource Include="Resources\Images\01_05.png" />
	  <AvaloniaResource Include="Resources\Images\01_06.png" />
	  <AvaloniaResource Include="Resources\Images\09028_01.jpg" />
	  <AvaloniaResource Include="Resources\Images\ac_0004_11_2.jpg" />
	  <AvaloniaResource Include="Resources\Images\antenna_tracker_01.png" />
	  <AvaloniaResource Include="Resources\Images\apm1.jpg" />
	  <AvaloniaResource Include="Resources\Images\apm2_5.jpg" />
	  <AvaloniaResource Include="Resources\Images\apm2.jpg" />
	  <AvaloniaResource Include="Resources\Images\apmp1.jpg" />
	  <AvaloniaResource Include="Resources\Images\apmp2.jpg" />
	  <AvaloniaResource Include="Resources\Images\apmp3.jpg" />
	  <AvaloniaResource Include="Resources\Images\apmp4.jpg" />
	  <AvaloniaResource Include="Resources\Images\apmp5.jpg" />
	  <AvaloniaResource Include="Resources\Images\apmp6.jpg" />
	  <AvaloniaResource Include="Resources\Images\apm_airframes_001.png" />
	  <AvaloniaResource Include="Resources\Images\apm_airframes_002.png" />
	  <AvaloniaResource Include="Resources\Images\apm_airframes_07.png" />
	  <AvaloniaResource Include="Resources\Images\apm_airframes_08.png" />
	  <AvaloniaResource Include="Resources\Images\apm_rover_firmware.png" />
	  <AvaloniaResource Include="Resources\Images\aw.png" />
	  <AvaloniaResource Include="Resources\Images\bgdark.jpg" />
	  <AvaloniaResource Include="Resources\Images\bg.jpg" />
	  <AvaloniaResource Include="Resources\Images\boat.png" />
	  <AvaloniaResource Include="Resources\Images\br_0004_03_2.jpg" />
	  <AvaloniaResource Include="Resources\Images\br_0016_01_3t.jpg" />
	  <AvaloniaResource Include="Resources\Images\br_apmpwrdean_2.jpg" />
	  <AvaloniaResource Include="Resources\Images\br_hmc5883_01_2.jpg" />
	  <AvaloniaResource Include="Resources\Images\bt_hc06.jpg" />
	  <AvaloniaResource Include="Resources\Images\calibration01.jpg" />
	  <AvaloniaResource Include="Resources\Images\calibration02.jpg" />
	  <AvaloniaResource Include="Resources\Images\calibration03.jpg" />
	  <AvaloniaResource Include="Resources\Images\calibration04.jpg" />
	  <AvaloniaResource Include="Resources\Images\calibration05.jpg" />
	  <AvaloniaResource Include="Resources\Images\calibration06.jpg" />
	  <AvaloniaResource Include="Resources\Images\calibration07.jpg" />
	  <AvaloniaResource Include="Resources\Images\cameragimalpitch1.png" />
	  <AvaloniaResource Include="Resources\Images\cameragimalroll1.png" />
	  <AvaloniaResource Include="Resources\Images\cameragimalyaw.png" />
	  <AvaloniaResource Include="Resources\Images\camera_icon_g.png" />
	  <AvaloniaResource Include="Resources\Images\camera_icon.png" />
	  <AvaloniaResource Include="Resources\Images\car.png" />
	  <AvaloniaResource Include="Resources\Images\configuration.png" />
	  <AvaloniaResource Include="Resources\Images\connect.png" />
	  <AvaloniaResource Include="Resources\Images\dark_connect_icon.png" />
	  <AvaloniaResource Include="Resources\Images\dark_disconnect_icon.png" />
	  <AvaloniaResource Include="Resources\Images\dark_flightdata_icon.png" />
	  <AvaloniaResource Include="Resources\Images\dark_flightplan_icon.png" />
	  <AvaloniaResource Include="Resources\Images\dark_help_icon.png" />
	  <AvaloniaResource Include="Resources\Images\dark_initialsetup_icon.png" />
	  <AvaloniaResource Include="Resources\Images\dark_simulation_icon.png" />
	  <AvaloniaResource Include="Resources\Images\dark_terminal_icon.png" />
	  <AvaloniaResource Include="Resources\Images\dark_tuningconfig_icon.png" />
	  <AvaloniaResource Include="Resources\Images\data.png" />
	  <AvaloniaResource Include="Resources\Images\disconnect.png" />
	  <AvaloniaResource Include="Resources\Images\donate.png" />
	  <AvaloniaResource Include="Resources\Images\down.png" />
	  <AvaloniaResource Include="Resources\Images\firmware.png" />
	  <AvaloniaResource Include="Resources\Images\flightdata.png" />
	  <AvaloniaResource Include="Resources\Images\flightplanner.png" />
	  <AvaloniaResource Include="Resources\Images\frames_01.png" />
	  <AvaloniaResource Include="Resources\Images\frames_02.png" />
	  <AvaloniaResource Include="Resources\Images\frames_03.png" />
	  <AvaloniaResource Include="Resources\Images\frames_04.png" />
	  <AvaloniaResource Include="Resources\Images\frames_05.png" />
	  <AvaloniaResource Include="Resources\Images\frames_06.png" />
	  <AvaloniaResource Include="Resources\Images\frames_07.png" />
	  <AvaloniaResource Include="Resources\Images\frames_08.png" />
	  <AvaloniaResource Include="Resources\Images\frames_h.png" />
	  <AvaloniaResource Include="Resources\Images\frames_plus.png" />
	  <AvaloniaResource Include="Resources\Images\frames.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_011.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_012.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_01.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_02.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_03.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_04.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_05.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_06.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_07.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_08.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_09.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_10.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_11.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_12.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_13.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_14.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_15.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_2013_logos_16.png" />
	  <AvaloniaResource Include="Resources\Images\fw_icons_y6.png" />
	  <AvaloniaResource Include="Resources\Images\gaugebg.png" />
	  <AvaloniaResource Include="Resources\Images\guagebg.jpg" />
	  <AvaloniaResource Include="Resources\Images\hardwareconfig02.png" />
	  <AvaloniaResource Include="Resources\Images\hardwareconfig.png" />
	  <AvaloniaResource Include="Resources\Images\heli.png" />
	  <AvaloniaResource Include="Resources\Images\helpwizard.png" />
	  <AvaloniaResource Include="Resources\Images\help.png" />
	  <AvaloniaResource Include="Resources\Images\hframelight.png" />
	  <AvaloniaResource Include="Resources\Images\hframe.png" />
	  <AvaloniaResource Include="Resources\Images\iconwarning32.png" />
	  <AvaloniaResource Include="Resources\Images\iconwarning48.png" />
	  <AvaloniaResource Include="Resources\Images\iris_fw_icon.png" />
	  <AvaloniaResource Include="Resources\Images\light_01.png" />
	  <AvaloniaResource Include="Resources\Images\light_03.png" />
	  <AvaloniaResource Include="Resources\Images\light_05.png" />
	  <AvaloniaResource Include="Resources\Images\light_06.png" />
	  <AvaloniaResource Include="Resources\Images\light_flightdata_icon.png" />
	  <AvaloniaResource Include="Resources\Images\light_flightplan_icon.png" />
	  <AvaloniaResource Include="Resources\Images\light_tuningconfig_icon.png" />
	  <AvaloniaResource Include="Resources\Images\maggps.png" />
	  <AvaloniaResource Include="Resources\Images\marker_01.png" />
	  <AvaloniaResource Include="Resources\Images\marker_02.png" />
	  <AvaloniaResource Include="Resources\Images\marker_03.png" />
	  <AvaloniaResource Include="Resources\Images\marker_04.png" />
	  <AvaloniaResource Include="Resources\Images\marker_05.png" />
	  <AvaloniaResource Include="Resources\Images\marker_06.png" />
	  <AvaloniaResource Include="Resources\Images\marker_07.png" />
	  <AvaloniaResource Include="Resources\Images\mavcmd.zh_hans.txt" />
	  <AvaloniaResource Include="Resources\Images\mavcmd.zh_tw.txt" />
	  <AvaloniaResource Include="Resources\Images\mavcmd.txt" />
	  <AvaloniaResource Include="Resources\Images\mavparam.zh_hans.txt" />
	  <AvaloniaResource Include="Resources\Images\mavparam.zh_tw.txt" />
	  <AvaloniaResource Include="Resources\Images\mavparam.txt" />
	  <AvaloniaResource Include="Resources\Images\minimosd.jpg" />
	  <AvaloniaResource Include="Resources\Images\missionplannerlogodark.png" />
	  <AvaloniaResource Include="Resources\Images\missionplannerlogo.png" />
	  <AvaloniaResource Include="Resources\Images\new_3dr_04.png" />
	  <AvaloniaResource Include="Resources\Images\new_frames_01.png" />
	  <AvaloniaResource Include="Resources\Images\new_frames_05x.png" />
	  <AvaloniaResource Include="Resources\Images\new_frames_05.png" />
	  <AvaloniaResource Include="Resources\Images\new_frames_06.png" />
	  <AvaloniaResource Include="Resources\Images\new_frames_09.png" />
	  <AvaloniaResource Include="Resources\Images\new_frames_10.png" />
	  <AvaloniaResource Include="Resources\Images\new_frames_11.png" />
	  <AvaloniaResource Include="Resources\Images\new_frames_12.png" />
	  <AvaloniaResource Include="Resources\Images\new_frames_13.png" />
	  <AvaloniaResource Include="Resources\Images\new_frames_14.png" />
	  <AvaloniaResource Include="Resources\Images\no_video.png" />
	  <AvaloniaResource Include="Resources\Images\octox.png" />
	  <AvaloniaResource Include="Resources\Images\parachute.png" />
	  <AvaloniaResource Include="Resources\Images\pixhawk2cube.jpg" />
	  <AvaloniaResource Include="Resources\Images\pixhawk.jpg" />
	  <AvaloniaResource Include="Resources\Images\plane2.png" />
	  <AvaloniaResource Include="Resources\Images\planebackground.png" />
	  <AvaloniaResource Include="Resources\Images\planetracker1.png" />
	  <AvaloniaResource Include="Resources\Images\planetracker2.png" />
	  <AvaloniaResource Include="Resources\Images\planetracker3.png" />
	  <AvaloniaResource Include="Resources\Images\planetracker4.png" />
	  <AvaloniaResource Include="Resources\Images\planetracker5.png" />
	  <AvaloniaResource Include="Resources\Images\planetracker6.png" />
	  <AvaloniaResource Include="Resources\Images\planetracker.png" />
	  <AvaloniaResource Include="Resources\Images\planner.png" />
	  <AvaloniaResource Include="Resources\Images\plusframesgreen_02.png" />
	  <AvaloniaResource Include="Resources\Images\plusframesgreen_04.png" />
	  <AvaloniaResource Include="Resources\Images\plusframesgreen_06.png" />
	  <AvaloniaResource Include="Resources\Images\plusframes_02.png" />
	  <AvaloniaResource Include="Resources\Images\plusframes_04.png" />
	  <AvaloniaResource Include="Resources\Images\plusframes_06.png" />
	  <AvaloniaResource Include="Resources\Images\px4flow1.jpg" />
	  <AvaloniaResource Include="Resources\Images\px4.jpg" />
	  <AvaloniaResource Include="Resources\Images\quad2.png" />
	  <AvaloniaResource Include="Resources\Images\quadframeslight_01.jpg" />
	  <AvaloniaResource Include="Resources\Images\quadframeslight_03.jpg" />
	  <AvaloniaResource Include="Resources\Images\quadframeslight_05.jpg" />
	  <AvaloniaResource Include="Resources\Images\quadframeslight_07.jpg" />
	  <AvaloniaResource Include="Resources\Images\quadframeslight_13.jpg" />
	  <AvaloniaResource Include="Resources\Images\quadframeslight_15.jpg" />
	  <AvaloniaResource Include="Resources\Images\quadframeslight_16.png" />
	  <AvaloniaResource Include="Resources\Images\quadframesnormal_01.png" />
	  <AvaloniaResource Include="Resources\Images\quadframesnormal_03.png" />
	  <AvaloniaResource Include="Resources\Images\quadframesnormal_05.png" />
	  <AvaloniaResource Include="Resources\Images\quadframesnormal_06.png" />
	  <AvaloniaResource Include="Resources\Images\quadframesnormal_11.png" />
	  <AvaloniaResource Include="Resources\Images\quadframesnormal_12.png" />
	  <AvaloniaResource Include="Resources\Images\quadframesnormal_14.png" />
	  <AvaloniaResource Include="Resources\Images\quadframes_01.jpg" />
	  <AvaloniaResource Include="Resources\Images\quadframes_03.jpg" />
	  <AvaloniaResource Include="Resources\Images\quadframes_05.jpg" />
	  <AvaloniaResource Include="Resources\Images\quadframes_07.jpg" />
	  <AvaloniaResource Include="Resources\Images\quadframes_13.jpg" />
	  <AvaloniaResource Include="Resources\Images\quadframes_15.jpg" />
	  <AvaloniaResource Include="Resources\Images\quadframes_16.png" />
	  <AvaloniaResource Include="Resources\Images\quadhover_01.png" />
	  <AvaloniaResource Include="Resources\Images\quadhover_03.png" />
	  <AvaloniaResource Include="Resources\Images\quadhover_05.png" />
	  <AvaloniaResource Include="Resources\Images\quadhover_06.png" />
	  <AvaloniaResource Include="Resources\Images\quadhover_11.png" />
	  <AvaloniaResource Include="Resources\Images\quadhover_12.png" />
	  <AvaloniaResource Include="Resources\Images\quadhover_14.png" />
	  <AvaloniaResource Include="Resources\Images\redsinglecopter2.png" />
	  <AvaloniaResource Include="Resources\Images\rover_10.png" />
	  <AvaloniaResource Include="Resources\Images\rover_11.png" />
	  <AvaloniaResource Include="Resources\Images\rover.png" />
	  <AvaloniaResource Include="Resources\Images\selectvehicle.png" />
	  <AvaloniaResource Include="Resources\Images\shutter.png" />
	  <AvaloniaResource Include="Resources\Images\simulation.png" />
	  <AvaloniaResource Include="Resources\Images\softwareconfig.png" />
	  <AvaloniaResource Include="Resources\Images\splashdark.jpg" />
	  <AvaloniaResource Include="Resources\Images\splash.jpg" />
	  <AvaloniaResource Include="Resources\Images\sub.png" />
	  <AvaloniaResource Include="Resources\Images\terminal.png" />
	  <AvaloniaResource Include="Resources\Images\uavcanesc.jpg" />
	  <AvaloniaResource Include="Resources\Images\up.png" />
	  <AvaloniaResource Include="Resources\Images\welcome_to_michael_oborne.rtf" />
	  <AvaloniaResource Include="Resources\Images\wizardicon1.png" />
	  <AvaloniaResource Include="Resources\Images\wizardicon.png" />
	  <AvaloniaResource Include="Resources\Images\x8.png" />
	  <AvaloniaResource Include="Resources\Images\y6.png" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="appsettings.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AsyncAwaitBestPractices.MVVM" />
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Controls.ItemsRepeater" />

		<PackageReference Include="Avalonia.Themes.Fluent" />
		<PackageReference Include="Avalonia.Fonts.Inter" />
		<PackageReference Include="LiveMarkdown.Avalonia" />

		<PackageReference Include="Material.Icons.Avalonia" />
		<PackageReference Include="CommunityToolkit.Mvvm" />

        <PackageReference Include="Irihi.Ursa" />
		<PackageReference Include="Irihi.Ursa.Themes.Semi" />

        <PackageReference Include="Semi.Avalonia" />
		<PackageReference Include="Semi.Avalonia.AvaloniaEdit" />
		<PackageReference Include="Semi.Avalonia.ColorPicker" />
		<PackageReference Include="Semi.Avalonia.DataGrid" />
		<PackageReference Include="Semi.Avalonia.Dock" />

		<PackageReference Include="Riok.Mapperly" />

		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Enrichers.Environment" />
		<PackageReference Include="Serilog.Enrichers.Thread" />
		<PackageReference Include="Serilog.Settings.AppSettings" />
		<PackageReference Include="Serilog.Sinks.Debug" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.Trace" />

		<PackageReference Include="Mapsui" />
        <PackageReference Include="Mapsui.Avalonia12" />
        <PackageReference Include="Mapsui.Tiling" />

        <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />

	</ItemGroup>

	<ItemGroup>
      <ProjectReference Include="..\..\Core\MissionPlanner.Shared.Models\MissionPlanner.Shared.Models.csproj" />
      <ProjectReference Include="..\..\Core\MissionPlanner.Simulation\MissionPlanner.Simulation.csproj" />
      <ProjectReference Include="..\..\Libraries\MissionPlanner.Library\MissionPlanner.Library.csproj" />
      <ProjectReference Include="..\..\Core\MissionPlanner.Core\MissionPlanner.Core.csproj" />
      <ProjectReference Include="..\..\Core\MissionPlanner.Maps\MissionPlanner.Maps.csproj" />
      <ProjectReference Include="..\..\Tools\MissionPlanner.Simulator\MissionPlanner.Simulator.csproj" />
      <ProjectReference Include="..\MissionPlanner.Library.Linux\MissionPlanner.Library.Linux.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Introduction\Content\Introduction.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <AvaloniaXaml Update="Views\Common\TopBarView.axaml">
	    <Generator>MSBuild:Compile</Generator>
	  </AvaloniaXaml>
	  <AvaloniaXaml Update="Views\Missions\MissionItemListView.axaml">
	    <Generator></Generator>
	  </AvaloniaXaml>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Views\InitSetup\InstallFirmware\InstallFirmwarePage.axaml.cs">
	    <DependentUpon>InstallFirmwarePage.axaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\InitSetup\InstallFirmware\SubViews\ConfirmDfuTargetView.axaml.cs">
	    <DependentUpon>ConfirmDfuTargetView.axaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\InitSetup\MandatoryHardware\Sections\HardwareIdView.axaml.cs">
	    <DependentUpon>HardwareIdView.axaml</DependentUpon>
	  </Compile>
	</ItemGroup>

</Project>
